[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "threatware"
authors = [{name = "Dave", email = "dave@samadhicsecurity.com"}]
dynamic = ["version", "description"]
